### ISSUE TITLE
I have some little problem to ask 

### ISSUE THREAD

**Issue by dele75** [nmileva/starfm4py#10]
When I run the code, a error like that occurs：cannot import name 'sizeSlices' from 'parameters' (D:\Anaconda3\envs\myenv\lib\site-packages\parameters_init_.py) what should I do next? 

I would be very grateful if you could save some time to answer my question.Thanks a lot.

**Comment by nmileva** [comment]
parameters.py should be in the same location as your code or you should explicitly point out the location of parameters.py in your script.
