### ISSUE TITLE
Parameters setting for Landsat and MODIS LST

### ISSUE THREAD

**Issue by suffenjoy** [nmileva/starfm4py#11]
Hi, thank you so much for your great work! I'm trying to use your script to fuse Landsat and MODIS land surface temperature. Have you done any experiment on that? Do you have any suggestions on the parameter settings for this task? Thanks!

**Comment by nmileva** [comment]
Hi, I haven't personally used STARFM for the fusion of Landsat and MODIS land surface temperature but there seem to be some papers out there that have done that already. For example: Zhu, X., Song, X., Leng, P., Li, X., Gao, L., Guo, D., & Cai, S. (2021). A framework for generating high spatiotemporal resolution land surface temperature in heterogeneous areas. Remote Sensing, 13(19), 3885.
