### ISSUE TITLE
ESTARM - help

### ISSUE THREAD

**Issue by gunjanthakuria** [nmileva/starfm4py#3]
Hi Mileva,

  Thanks the code was very useful and helpful in understanding the implementation of STARFM. I am working on fusing the Thermal bands of Modis and Landsat data to produce daily Land Surface Temperature (LST) at Landsat Resolution .
     While STARFM is useful to start off, I would like to understand if you have also implemented ESTARFM  in python and could guide is on that. 

Thanks ,
Gunjan

**Comment by nmileva** [comment]
Hi Gunjan,
I'm happy this implementation was useful for you. I haven't worked on the implementation of ESATRFM.

**Comment by meng70** [comment]
> 嗨，米列娃，
> 
> 感谢代码非常有用，有助于理解 STARFM 的实现。我正在努力融合 Modis 和 Landsat 数据的热波段，以在 Landsat 分辨率下生成每日地表温度 (LST)。 虽然 STARFM 在开始时很有用，但我想了解您是否也在 python 中实现了 ESTARFM 并且可以指导。
> 
> 谢谢， 甘扬



> 嗨，米列娃，
> 
> 感谢代码非常有用，有助于理解 STARFM 的实现。我正在努力融合 Modis 和 Landsat 数据的热波段，以在 Landsat 分辨率下生成每日地表温度 (LST)。 虽然 STARFM 在开始时很有用，但我想了解您是否也在 python 中实现了 ESTARFM 并且可以指导。
> 
> 谢谢， 甘扬

Hi，Gunjan
I am also working on generating LST data using ESTARFM model in python recently, have you done it? Could you please share the code below if possible?
Many thangs

**Comment by cindyip-rgb** [comment]
hi, Gunjan. could you please share the code of ESTARFM? Thanks in advance.
