### ISSUE TITLE
ValueError: Chunks and shape must be of the same length/dimension.

### ISSUE THREAD

**Issue by chenxinnum1** [nmileva/starfm4py#5]
Hello, 
I have fused Landsat and MODIS with this code. Actually it works, thank you very much for your share.
But the problem I faced is the predicted landsat-like image is a single-band image.
So I tried to change the code in test.py and starfm4py.py. 
For example I changed the read(1) to read(), and change ‘’the profile.update(dtype='float64', count=1) to ‘’the profile.update(dtype='float64', count=2) ‘’. However, the ValueError ‘’Chunks and shape must be of the same length/dimension‘’ is generated.
So what I want to know is how to modify the code in a right way.
Best regards,
Xin

**Comment by nmileva** [comment]
Hi Xin,

I would suggest you only make changes to test.py. You can try to read all the bands of the image with a for loop. Then, just put all the code from test.py inside the for loop. Thus, the new bands will be predicted one at a time. Also, don't forget to change the name of the output (file_name) with each iteration, so the results are not overwritten. Hope this helps!

BR,
Nikolina

**Comment by chenxinnum1** [comment]
Nikolina，

Thanks for your share of code and kind reply. I will try again later. Thanks~

Best,
Xin




| |
chenxin
|
|
邮箱：chenxinnum1@163.com
|

Signature is customized by Netease Mail Master

On 11/27/2019 08:21, Nikolina Mileva wrote:

Closed #5.
