### ISSUE TITLE
Some questions I want to ask

### ISSUE THREAD

**Issue by WongYinJ** [nmileva/starfm4py#8]
Firstly, thank you for your contribution, your code is of great help to me. If it won't bother you too much, I have some little problem to ask you for.
  1' How do you evaluate the method. I calculated the PSNR between the result and the GT(groundtruth ), but it's only -44.17. In what way should I do it correctly.
  2' The demo 'test' seems to only deal with images with only one spectral band. If I want to use it on hyperspectral images, what should I do? Should I just do it band by band through a 'for' iteration?

  I would be very grateful if you could save some time to answer my question

**Comment by nmileva** [comment]
Hi, to your questions:
1. It's up to you to decide which metric you want to use for the evaluation of the results. Besides PSNR, you can look also at the RMSE, ERGAS, the correlation coefficient between the images.
2. Check https://github.com/nmileva/starfm4py/issues/5
